list=[546,'ram',100,10,11,56,'vihgnesh',7738,859]
print("printing the list")
print(list)
print("printing the values using the negative index ex list[-1]")
print(list[-1])
print("printing the list in the given index range ex list[2:5]")
print(list[2:5])
print("printing the list in the givenn sequence of the index like lsit[-1:-9:-1]")
print(list[-1:-9:-1])
print("printing the list like list[:]")
print(list[:])
print("printing the list like list[5:]")
print(list[5:])
print ("printing the list like list[:7]")
print(list[:7])
print("printing the list like given sequence of the index like list[-3:-1:-2]")
print(list[-3:-1:-2])
print("printing the list with the negative index ")
print(list[-1:])
print("updating the value of the list like list[1]=0")
list[1]=0
print("appending the value of 113 in the list ")
list.append(113)
print("printing the list")
print(list)
print("deleting an item from the list like  list.__delitem__(1)")
list.__delitem__(1)
print("printing the final list after all the operations")
print(list)
