
print("this program is to demonstrate the string functions \n ")
str=input("enter the string to apply the string functions")
print("upper to convert all the string to the upper case ::-->>"+str.upper())
print("lower to conver all the string to lower case ::-->>"+str.lower())
print("capitalize to make the first alphabate capital in the string ::-->>"+str.capitalize())
print("isalnum to check wheather the given string is the alpha numeric ::-->>"+str.isalnum())
print("isalpha to check wheather the given string is alphabatical or not ::-->>"+str.isalpha())
print("is digit to check wheather the given string is in the digit form are not ::-->>"+str.isdigit())
print("isnumeric to check wheather the given string is in the numeric form are not ::-->>"+str.isnumeric())
print("isdecimal to check wheather the given string is in the decimal ::-->>"+str.isdecimal())
print("is upper to check wheather the given string is in the upper case or not ::-->> "+str.isupper())
print("is lower to check wheather the given string is in the lower case or not ::-->>"+str.islower())
print("is title to check wheather the given string is in the 'title' ::-->>"+str.istitle())
print("is space to check wheather the given string is in the  only whitespace ::-->>"+str.isspace())

